// แก้ข้อมูลผลงานได้ที่ไฟล์นี้ไฟล์เดียว
const PROJECTS = [
  {
    id: "short-film",
    number: "01",
    title: "ภาพความทรงจำ",
    category: "SHORT FILM",
    year: "2025",
    cover: "assets/project-01-cover.jpg",
    previewVideo: "assets/1.mp4",
    fullVideoUrl: "https://youtu.be/zCyQyW--qZs?si=7qJ0BBYGQvak4lca",
    role: "Director / DOP / Colorist",
    intro: "โปรเจกต์ภาพยนตร์สั้นภายในรายวิชา ถ่ายทอดเรื่องราวผ่านกระบวนการกำกับ ตัดต่อ และเกรดสี",
    overview: "“ภาพความทรงจำ” เป็นภาพยนตร์สั้นที่นำเสนอเรื่องราวเกี่ยวกับความทรงจำ ความผูกพัน และช่วงเวลาที่ไม่สามารถย้อนกลับไปแก้ไขได้ ถ่ายทอดผ่านบรรยากาศของภาพ แสง และจังหวะการเล่าเรื่อง เพื่อให้ผู้ชมค่อย ๆ รับรู้ความรู้สึกของตัวละครและตีความเรื่องราวผ่านประสบการณ์ของตนเอง",
    process: "เริ่มต้นจากการพัฒนาแนวคิดและกำหนดทิศทางของเรื่อง ก่อนนำมาจัดทำบทภาพยนตร์ วางลำดับเหตุการณ์ และออกแบบภาพผ่าน Storyboard จากนั้นจึงวางแผนการถ่ายทำ ทั้งด้านสถานที่ องค์ประกอบภาพ แสง และการเคลื่อนกล้อง ในขั้นตอนหลังการถ่ายทำ ได้คัดเลือกฟุตเทจ เรียบเรียงลำดับภาพ ออกแบบจังหวะการตัดต่อ และปรับโทนสี เพื่อสร้างบรรยากาศที่สอดคล้องกับอารมณ์และความหมายของเรื่อง",
    contribution: "รับผิดชอบในบทบาทผู้กำกับ ผู้ตัดต่อ และผู้ปรับแต่งสีของภาพยนตร์ โดยดูแลตั้งแต่การตีความบท กำหนดแนวทางการแสดง วางองค์ประกอบภาพ และควบคุมบรรยากาศระหว่างการถ่ายทำ ไปจนถึงการตัดต่อและเกรดสีในขั้นตอน Post-production",
    credits: ["Production: [ชื่อทีม]", "Camera: [รุ่นกล้อง / เลนส์]", "Duration: [ระยะเวลา]"],
    gallery: ["assets/project-01-gallery-1.jpg", "assets/project-01-gallery-2.jpg", "assets/project-01-gallery-3.jpg"]
  },
  {
    id: "commercial",
    number: "02",
    title: "THROUGH THE HUSTLE",
    category: "SHORT FILM",
    year: "2025",
    cover: "assets/project-02-cover.jpg",
    previewVideo: "assets/2.mp4",
    fullVideoUrl: "https://www.youtube.com/watch?v=RZPY1lr7Bas&t=1s",
    role: "Director / DOP / Coloris",
    intro: "Short film Basketball Transition โปรเจกต์ภาพยนตร์สั้นภายในรายวิชา ฝึกการกำกับภาพ การจัดแสง และการเกรดสี",
    overview: "ภาพยนตร์สั้นแนวกีฬาบาสเกตบอล ถ่ายทอดเรื่องราวของความพยายามและการก้าวข้ามขีดจำกัด ผ่านการเล่าเรื่องด้วยภาพ แสง และจังหวะการตัดต่อ",
    process: "พัฒนาแนวคิด วางแผนการถ่ายทำ ควบคุมภาพและแสงระหว่าง Production รวมถึงตัดต่อและเกรดสีเพื่อสร้าง Mood & Tone ของภาพยนตร์",
    contribution: "รับผิดชอบตำแหน่ง Director / DOP / Colorist ดูแลการกำกับภาพ การจัดแสง มุมกล้อง และการปรับสีในขั้นตอน Post-production",
    credits: ["Client: [ชื่อแบรนด์]", "Agency: [ถ้ามี]", "Deliverables: [เช่น 16:9 / 9:16]"],
    gallery: ["assets/project-02-gallery-1.jpg", "assets/project-02-gallery-2.jpg", "assets/project-02-gallery-3.jpg"]
  },
  {
    id: "music-video",
    number: "03",
    title: "ไฟต์สุดท้าย Last Bout",
    category: "SHORT FILM",
    year: "2025",
    cover: "assets/project-03-cover.jpg",
    previewVideo: "assets/3.mp4",
    fullVideoUrl: "https://www.youtube.com/watch?v=-A8LKJcPT2E&t=1s",
    role: "Director / Editor",
    intro: "ภาพยนต์สั้นนี้จัดทำในค่าย OFOS NEXT FRAME  :  ค่ายพัฒนาศักยภาพการผลิตภาพยนตร์แอ็กชัน สำหรับนิสิตนักศึกษาระดับอุดมศึกษามาในรูปแบบหนัง Action ระยะเวลาการถ่ายทำ 2 วัน",
    overview: "ภาพยนตร์สั้นแนว Action ที่จัดทำในค่าย OFOS NEXT FRAME ถ่ายทอดเรื่องราวการแข่งขันและความขัดแย้งผ่านการเล่าเรื่องด้วยภาพและจังหวะการต่อสู้",
    process: "วางแผนแนวคิดและลำดับฉาก ควบคุมการถ่ายทำในระยะเวลาจำกัด รวมถึงตัดต่อและเรียบเรียงภาพเพื่อสร้างความต่อเนื่องและอารมณ์ของเรื่อง",
    contribution: "รับผิดชอบในส่วนเขียนบท ติดต่อประสานงานไม่ว่าจะนักแสดงหรือโลเคชั่นและควบกับตำแหน่ง Director / Editor ดูแลการกำกับภาพรวมของเรื่อง การควบคุมการถ่ายทำ และการตัดต่อภาพยนตร์ในขั้นตอน Post-production",
    credits: ["Artist: [ชื่อศิลปิน]", "Track: [ชื่อเพลง]", "Runtime: [ความยาว]"],
    gallery: ["assets/project-03-gallery-1.jpg", "assets/project-03-gallery-2.jpg", "assets/project-03-gallery-3.jpg"]
  },
  {
    id: "documentary",
    number: "04",
    title: "พนันคือกับดักชีวิต",
    category: "โฆษณา",
    year: "2026",
    cover: "assets/project-04-cover.jpg",
    previewVideo: "assets/4.mp4",
    fullVideoUrl: "https://youtu.be/_oOxiBekvUk?si=4jKAeD5lyr9jzrI-",
    role: "DOP / Editor Colorist",
    intro: "เป็นโฆษณาผลกระทบของ (พนัน) สไตล์ Comedy ซึ่งเป็นงานในรายวิชาที่ได้มีโอกาสลองทำอีกครั้งจากที่เรียนรู้ข้อผิดพลาดมาหลายโปรเจกต์",
    overview: "โฆษณารณรงค์เกี่ยวกับผลกระทบของการพนัน ถ่ายทอดแนวคิดเรื่องการตัดสินใจและผลลัพธ์ที่ตามมา ผ่านการเล่าเรื่องด้วยภาพและอารมณ์",
    process: "วางแนวคิดและออกแบบภาพให้สื่อสารประเด็นของงาน ควบคุมการถ่ายภาพ การจัดแสง และปรับโทนสีเพื่อสร้างบรรยากาศให้เหมาะกับเนื้อหา",
    contribution: "มีส่วนร่วมในการคิดบทและรับผิดชอบตำแหน่ง DOP / Colorist ดูแลการออกแบบภาพ การจัดแสง การควบคุม Mood & Tone และการเกรดสีในขั้นตอน Post-production เพื่อให้ภาพสื่อสารอารมณ์และแนวคิดของผลงาน",
    credits: ["Subject: [หัวข้อ]", "Location: [สถานที่]", "Format: [รูปแบบ]"],
    gallery: ["assets/project-04-gallery-1.jpg", "assets/project-04-gallery-2.jpg", "assets/project-04-gallery-3.jpg"]
  },
  {
    id: "social-content",
    number: "05",
    title: "บักหล่า",
    category: "SHORT FILM",
    year: "2025",
    cover: "assets/project-05-cover.jpg",
    previewVideo: "assets/5.mp4",
    fullVideoUrl: "https://youtu.be/Nfhscrl5iTo?si=_pZ5seU6wR4xhWQ_",
    role: "AD / Actor / Editor Colorist",
    intro: "ภาพยนต์สั้นนี้จัดทำในค่าย OFOS NEXT FRAME  :  ค่ายพัฒนาศักยภาพการผลิตภาพยนตร์อีสาน สำหรับนิสิตนักศึกษาระดับอุดมศึกษามาในรูปแบบหนัง ESAN",
    overview: "ภาพยนตร์สั้นอีสานจากค่าย OFOS NEXT FRAME ถ่ายทอดเรื่องราวและวิถีชีวิตผ่านมุมมองของคนรุ่นใหม่ ด้วยการเล่าเรื่องแบบภาพยนตร์ ESAN",
    process: "ร่วมพัฒนาแนวทางการแสดง ทำความเข้าใจบทบาทตัวละคร และสนับสนุนการทำงานของทีมกำกับระหว่างการถ่ายทำ รวมถึงร่วมจัดการลำดับงานภายในกองถ่าย",
    contribution: "รับผิดชอบตำแหน่ง AD / Actor / Eiditor Colorist ทำหน้าที่ช่วยประสานงานและสนับสนุนทีมผู้กำกับ พร้อมรับบทเป็นนักแสดง ถ่ายทอดอารมณ์และเรื่องราวของตัวละครตามแนวทางที่กำหนด ควบกับการตัดต่อและเกรดสีเพื่อเรียบเรียงเนื้อหาและอารมณ์",
    credits: ["Platform: [TikTok / Reels / YouTube]", "Episodes: [จำนวน]", "Format: [9:16 / 1:1]"],
    gallery: ["assets/project-05-gallery-1.jpg", "assets/project-05-gallery-2.jpg", "assets/project-05-gallery-3.jpg"]
  },
  {
    id: "color-study",
    number: "06",
    title: "บ้านหลังสุดท้าย",
    category: "SHORT FILM",
    year: "2025",
    cover: "assets/project-06-cover.jpg",
    previewVideo: "assets/6.mp4",
    fullVideoUrl: "https://youtu.be/A_Rq_f_PX7I?si=GZ94DBHca6oD1vve",
    role: "Director / Editor Colorist",
    intro: "เป็นภาพยนต์สั้นเชิงสารคดี เรื่องราวของ “อาชีพคนขายโลงศพ” อาชีพที่หลายคนอาจไม่เคยหันมามอง",
    overview: "ภาพยนตร์สั้นเชิงสารคดี ถ่ายทอดเรื่องราวของ “อาชีพคนขายโลงศพ” ผ่านมุมมองชีวิต ความเชื่อ และเบื้องหลังอาชีพที่หลายคนอาจไม่เคยเข้าใจ",
    process: "พัฒนาแนวคิดและวางโครงสร้างการเล่าเรื่อง วางแผนการถ่ายทำ เก็บภาพและบทสัมภาษณ์ ก่อนนำมาตัดต่อเพื่อเรียบเรียงเรื่องราวและอารมณ์ของสารคดี",
    contribution: "รับผิดชอบตำแหน่ง Director / Editor ดูแลการกำหนดทิศทางของเรื่อง การวางลำดับเนื้อหา การควบคุมการถ่ายทำ และการตัดต่อเพื่อถ่ายทอดมุมมองของตัวละครและประเด็นของสารคดี",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-06-gallery-1.jpg", "assets/project-06-gallery-2.jpg", "assets/project-06-gallery-3.jpg"]
  },
  {
    id: "project-07",
    number: "07",
    title: "เช็คสติและอย่าหลงเชื่อ Ai ตื่นรู้...ตื่นโกง",
    category: "โฆษณา",
    year: "2026",
    cover: "assets/project-07-cover.jpg",
    previewVideo: "assets/7.mp4",
    fullVideoUrl: "https://www.youtube.com/watch?v=aRlaX9UuNew",
    role: "Director / Editor / Colorist",
    intro: "ได้รับ 1 ใน 10 ผลงานยอดเยี่ยมและได้เข้าไป Work Shop กับผู้กำกับชื่อดังและทีมงาน Good Take ที่มหาวิทยาลัยธรรมศาสตร์",
    overview: "ผลงานโฆษณารณรงค์เกี่ยวกับการรู้เท่าทันมิจฉาชีพและข่าวสารหลอกลวง ถ่ายทอดแนวคิดการตรวจสอบข้อมูลก่อนเชื่อ ผ่านการเล่าเรื่องที่เข้าใจง่ายและเข้าถึงผู้ชม",
    process: "พัฒนาแนวคิด วางโครงสร้างการเล่าเรื่อง ควบคุมการถ่ายทำ และดำเนินการตัดต่อพร้อมปรับโทนสี เพื่อสร้างอารมณ์และสื่อสารประเด็นของผลงานให้ชัดเจน",
    contribution: "รับผิดชอบตำแหน่ง Director / Editor / Colorist ดูแลการกำกับภาพรวม การเรียบเรียงเรื่องราวผ่านการตัดต่อ และออกแบบ Mood & Tone ด้วยการเกรดสีในขั้นตอน Post-production",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-07-gallery-1.jpg", "assets/project-07-gallery-2.jpg", "assets/project-07-gallery-3.jpg"]
  },
  {
    id: "project-08",
    number: "08",
    title: "มหาชัยกรุ๊ป เดลิเวอรี่",
    category: "โฆษณา",
    year: "2025",
    cover: "assets/project-08-cover.jpg",
    previewVideo: "assets/8.mp4",
    fullVideoUrl: "https://web.facebook.com/share/v/14qwpn1bgJc/",
    role: "Slate",
    intro: "ร่วมทำงานกับ KK Studio และนักแสดงโฆษณาชื่อดังที่จังหวัดขอนแก่น",
    overview: "ผลงานโฆษณาร่วมกับ KK Studio และนักแสดงโฆษณาในตำนาน ถ่ายทอดเรื่องราวของแบรนด์ผ่านการเล่าเรื่องแบบโฆษณา",
    process: "เรียนรู้และปฏิบัติงานในกองถ่ายจริง สนับสนุนการทำงานของทีม Production พร้อมประสานงานด้านลำดับการถ่ายทำและการบันทึกข้อมูลแต่ละ Take",
    contribution: "รับผิดชอบตำแหน่ง Slate ดูแลการบันทึก Scene / Shot / Take ให้ถูกต้อง เพื่อสนับสนุนการทำงานของทีมผู้กำกับและฝ่ายตัดต่อในขั้นตอน Post-production",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-08-gallery-1.jpg", "assets/project-08-gallery-2.jpg", "assets/project-08-gallery-3.jpg"]
  },
  {
    id: "project-09",
    number: "09",
    title: "INFORMAL DEBT",
    category: "SHORT FILM",
    year: "2025",
    cover: "assets/project-09-cover.jpg",
    previewVideo: "assets/9.mp4",
    fullVideoUrl: "https://youtu.be/GGHmVqOZv-8?si=RYXW694_RCgD004H",
    role: "Director / Editor",
    intro: "หนังสั้นในรายวิชาเรื่องแรกของการเรียนรู้ระบบ Production ทั้งเรื่องของการกำกับ การจัดแสง และการลำดับภาพ",
    overview: "ภาพยนตร์สั้นที่นำเสนอประเด็นปัญหาหนี้นอกระบบ ชายที่ติดการพนันจนต้องเลือกเส้นทางสีเทาเพื่อหาเงินมาใช้หนี้ที่ตนสร้างไว้ความหวังที่พังทลาย… กับเส้นทางที่ไม่มีทางกลับ",
    process: "พัฒนาแนวคิดและโครงสร้างเรื่อง วางแผนการถ่ายทำ ควบคุมการกำกับภาพ และเรียบเรียงลำดับภาพผ่านการตัดต่อเพื่อสื่อสารอารมณ์และเนื้อหาของเรื่อง",
    contribution: "รับผิดชอบตำแหน่ง Director / Editor ดูแลการกำหนดทิศทางของเรื่อง การควบคุมการถ่ายทำ และการตัดต่อเพื่อสร้างจังหวะการเล่าเรื่องและถ่ายทอดประเด็นของภาพยนตร์",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-09-gallery-1.jpg", "assets/project-09-gallery-2.jpg", "assets/project-09-gallery-3.jpg"]
  },
  {
    id: "project-10",
    number: "10",
    title: "Remember - Basketball",
    category: "คลิปสั้น",
    year: "2026",
    cover: "assets/project-10-cover.jpg",
    previewVideo: "assets/10.mp4",
    fullVideoUrl: "https://www.youtube.com/watch?v=PGVtMY1YwBM",
    role: "Director of Photography",
    intro: "หนังสั้น Basketball ที่ได้ลองการตัดต่อใหม่ๆ เพื่อให้ได้สเกลงานตามยุคสมัยปัจจุบัน",
    overview: "ภาพยนตร์สั้นแนวกีฬาบาสเกตบอล ที่นำเสนอเรื่องราวผ่านความทรงจำและความผูกพันกับกีฬา ถ่ายทอดอารมณ์ผ่านภาพและบรรยากาศในรูปแบบร่วมสมัย",
    process: "วางแนวทางภาพและองค์ประกอบการถ่ายทำ ออกแบบมุมกล้อง การจัดแสง และการเคลื่อนกล้อง เพื่อสร้าง Mood & Tone ให้สอดคล้องกับเรื่องราว",
    contribution: "รับผิดชอบตำแหน่ง DOP (Director of Photography) ดูแลการออกแบบภาพ การจัดแสง การเลือกมุมกล้อง และควบคุมคุณภาพด้านภาพให้เป็นไปตามแนวคิดของภาพยนตร์",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-10-gallery-1.jpg", "assets/project-10-gallery-2.jpg", "assets/project-10-gallery-3.jpg"]
  },
  {
    id: "project-11",
    number: "11",
    title: "นึกย้อนวันเก่า",
    category: "MV",
    year: "2026",
    cover: "assets/project-11-cover.jpg",
    previewVideo: "assets/11.mp4",
    fullVideoUrl: "https://youtu.be/wlXUdG6TC_8?si=qqBgsCtWVwOx_lgf",
    role: "Director / Editor Colorist",
    intro: "Music Video ที่เป็นผลงานตนเอง รวมทั้งการกำกับควบกับแสดง",
    overview: "Music Video ที่ถ่ายทอดเรื่องราวของความทรงจำและช่วงเวลาที่ผ่านไป ผ่านภาพ บรรยากาศ และอารมณ์ของเพลง",
    process: "พัฒนาแนวคิดและรูปแบบการเล่าเรื่องให้สอดคล้องกับเพลง วางแผนการถ่ายทำ ออกแบบภาพและบรรยากาศ ก่อนนำมาตัดต่อและปรับโทนสีเพื่อสร้าง Mood & Tone ของผลงาน",
    contribution: "รับผิดชอบตำแหน่ง Director / Editor / Colorist ดูแลตั้งแต่การกำหนดแนวทางของ Music Video การควบคุมการถ่ายทำ การเรียบเรียงภาพผ่านการตัดต่อ และการเกรดสีเพื่อสร้างเอกลักษณ์ทางภาพ",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-11-gallery-1.jpg", "assets/project-11-gallery-2.jpg", "assets/project-11-gallery-3.jpg"]
  },
  {
    id: "project-12",
    number: "12",
    title: "เงาแทนคน",
    category: "คลิปสั้น",
    year: "2025",
    cover: "assets/project-12-cover.jpg",
    previewVideo: "assets/12.mp4",
    fullVideoUrl: "https://drive.google.com/file/d/1lpK1GxC2PvO7igdvzhb-0CXAsLMHCHIN/view?usp=sharing",
    role: "Director of Photography",
    intro: "ตัวอย่างภาพยนต์ส่งประกวดเทศกาลเมืองแคน เรื่องราวของคนจนที่โดนคนรวยกดหัวจนไม่มีจุดยืน เขาไม่มีทางเลือกจึงรับหน้าให้การกระทำผิด",
    overview: "ภาพยนตร์สั้นส่งประกวดในเทศกาลเมืองแก่น เป็นผลงานที่ได้ทดลองถ่ายทอดเรื่องราวผ่านภาษาภาพและการเล่าเรื่อง แม้ไม่ได้ผ่านเข้ารอบการแข่งขัน แต่เป็นโปรเจกต์ที่ได้เรียนรู้กระบวนการผลิตภาพยนตร์จริง และเป็นหนึ่งในผลงานที่ภาคภูมิใจจากการทำงานร่วมกันของทีม",
    process: "ออกแบบแนวทางภาพให้สอดคล้องกับอารมณ์ของเรื่อง วางแผนการจัดแสง องค์ประกอบภาพ และมุมกล้อง เพื่อสร้างบรรยากาศที่สะท้อนความโดดเดี่ยวและความขัดแย้งของตัวละคร",
    contribution: "รับผิดชอบตำแหน่ง Director of Photography (DOP) ดูแลการออกแบบภาพ การจัดแสง การเลือกมุมกล้อง และควบคุม Mood & Tone ของภาพยนตร์ เพื่อสนับสนุนการเล่าเรื่องผ่านภาษาภาพ",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-12-gallery-1.jpg", "assets/project-12-gallery-2.jpg", "assets/project-12-gallery-3.jpg"]
  },
  {
    id: "project-13",
    number: "13",
    title: "ซ่อนขวัญ (Hidden Soul)",
    category: "SHORT FILM",
    year: "2026",
    cover: "assets/project-13-cover.jpg",
    previewVideo: "assets/13.mp4",
    fullVideoUrl: "https://www.youtube.com/watch?v=-nVAvTxNz60&t=702s",
    role: "Gaffer",
    intro: "ร่วมโปรเจกต์รุ่นพี่ในตำแหน่ง Gaffer ควบคุม Mood ของเรื่อง",
    overview: "ภาพยนตร์สั้นที่ร่วมพัฒนาในตำแหน่ง Gaffer โดยมุ่งเน้นการสร้างบรรยากาศและอารมณ์ของเรื่องผ่านการออกแบบแสง เพื่อสนับสนุนการเล่าเรื่องและความรู้สึกของตัวละคร",
    process: "ทำงานร่วมกับผู้กำกับภาพ (DOP) เพื่อวางแนวทางแสงของแต่ละฉาก ทดลองและจัดวางตำแหน่งไฟ ควบคุมทิศทาง แสงเงา และคุณภาพของแสงให้สอดคล้องกับ Mood & Tone ของภาพยนตร์",
    contribution: "รับผิดชอบตำแหน่ง Gaffer ดูแลการจัดแสงในกองถ่าย ควบคุมอุปกรณ์และทีมไฟ รวมถึงปรับแก้แสงหน้างานเพื่อให้ภาพที่ได้ตรงตามแนวทางภาพยนตร์",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-13-gallery-1.jpg", "assets/project-13-gallery-2.jpg", "assets/project-13-gallery-3.jpg"]
  },
  {
    id: "project-14",
    number: "14",
    title: "โมหะ",
    category: "SHORT FILM",
    year: "2026",
    cover: "assets/project-14-cover.jpg",
    previewVideo: "assets/14.mp4",
    fullVideoUrl: "",
    role: "Gaffer",
    intro: "ตัวอย่างหนังสั้นที่ร่วมกับเพื่อนทำหน้าที่ Gaffer ปัจจุบันอยู่ในช่วงลำดับภาพ ซึ่งผลงานเต็มจะฉายวันที่ 19 สิงหาคม 2569",
    overview: "ภาพยนตร์สั้นที่ร่วมพัฒนาในตำแหน่ง Gaffer อยู่ในขั้นตอนการผลิต โดยมุ่งเน้นการออกแบบแสงเพื่อสร้างบรรยากาศและสนับสนุนการเล่าเรื่องผ่านภาพยนตร์",
    process: "ทำงานร่วมกับทีมกำกับภาพในการวางแนวทางแสงของแต่ละฉาก เตรียมอุปกรณ์ไฟ ทดลองแสง และควบคุมทิศทางของแสงให้สอดคล้องกับ Mood & Tone ของเรื่อง",
    contribution: "รับผิดชอบตำแหน่ง Gaffer ดูแลการจัดแสงภายในกองถ่าย ควบคุมอุปกรณ์และการทำงานของทีมไฟ พร้อมปรับแก้แสงหน้างานเพื่อให้ได้ภาพตามแนวทางที่กำหนด",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-13-gallery-1.jpg", "assets/project-13-gallery-2.jpg", "assets/project-13-gallery-3.jpg"]
  },
  {
    id: "project-15",
    number: "15",
    title: "ท่วงทำนองไร้เสียง",
    category: "SHORT FILM",
    year: "2026",
    cover: "assets/project-15-cover.jpg",
    previewVideo: "assets/15.mp4",
    fullVideoUrl: "",
    role: "Director of Photography",
    intro: "หนังสั้นที่ได้ร่วมกับเพื่อนในหน้าที่ DOP ผลงานเต็มยังไม่ระบุแน่ชัด",
    overview: "ภาพยนตร์สั้นที่ร่วมพัฒนากับทีมในตำแหน่ง Director of Photography โดยมุ่งเน้นการถ่ายทอดเรื่องราวผ่านภาษาภาพ การจัดองค์ประกอบ และบรรยากาศของภาพยนตร์",
    process: "ร่วมวางแนวทางภาพกับทีมกำกับ ออกแบบมุมกล้อง การจัดแสง และองค์ประกอบภาพ เพื่อสร้าง Mood & Tone ให้สอดคล้องกับอารมณ์และแนวคิดของเรื่อง",
    contribution: "รับผิดชอบตำแหน่ง Director of Photography (DOP) ดูแลการออกแบบภาพ การวางมุมกล้อง การควบคุมแสง และคุณภาพของภาพระหว่างการถ่ายทำ เพื่อสนับสนุนการเล่าเรื่องผ่านภาพยนตร์",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-13-gallery-1.jpg", "assets/project-13-gallery-2.jpg", "assets/project-13-gallery-3.jpg"]
  },
  {
    id: "project-16",
    number: "16",
    title: "เงา",
    category: "SHORT FILM",
    year: "2026",
    cover: "assets/project-16-cover.jpg",
    previewVideo: "assets/16.mp4",
    fullVideoUrl: "https://drive.google.com/file/d/1PZZBFQ1JkIoeIuwywbqhPd3ZeOvhmoE-/view?usp=sharing",
    role: "DOP / Editor Colorist",
    intro: "หนังสั้นร่วมกับนิเทศน์ศาสตร์ โปรเจกต์กำกับเดี่ยว เรื่องราวของหญิงสาวป่วยเป็นโรคซึมเศร้าและปิดชีพเพื่อนตัวเอง เธอโดนวิญญาณตามติดจึงต้องคิดวิธีหนทางไสยศาสตร์",
    overview: "ภาพยนตร์สั้นกำกับเดี่ยวที่รับผิดชอบกระบวนการผลิตตั้งแต่การออกแบบภาพ การเล่าเรื่อง ไปจนถึงการตัดต่อและปรับสี ถ่ายทอดอารมณ์ของเรื่องผ่านแสง เงา และบรรยากาศของภาพยนตร์",
    process: "พัฒนาแนวคิดและวางรูปแบบการเล่าเรื่อง ออกแบบภาพ มุมกล้อง และแสงให้สอดคล้องกับอารมณ์ของเรื่อง ก่อนดำเนินการตัดต่อและเกรดสีเพื่อสร้าง Mood & Tone ของผลงาน",
    contribution: "รับผิดชอบตำแหน่ง DOP / Editor / Colorist ดูแลการกำหนดแนวทางภาพ การถ่ายทำ การเรียบเรียงลำดับภาพ และการปรับโทนสีในขั้นตอน Post-production เพื่อควบคุมทิศทางของภาพยนตร์ทั้งหมด",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-13-gallery-1.jpg", "assets/project-13-gallery-2.jpg", "assets/project-13-gallery-3.jpg"]
  },
  {
    id: "project-17",
    number: "17",
    title: "Better Call Saul Shot",
    category: "คลิปสั้น",
    year: "2026",
    cover: "assets/project-17-cover.jpg",
    previewVideo: "assets/17.mp4",
    fullVideoUrl: "https://youtu.be/NhWuvCCQI34?si=DGFolkYNNaAMf39f",
    role: "Director of Photography",
    intro: "ผลงานที่รวมตัวทำกับเพื่อนๆ เพื่อฝึกงานการเกรดสีหลังจากที่ได้ลองเรียนรู้สะสมกันมาหลายๆอย่าง",
    overview: "ผลงานทดลองถ่ายภาพยนตร์ร่วมกับเพื่อน เพื่อฝึกฝนการออกแบบภาพ การจัดแสง และการเกรดสี โดยนำแนวคิดจากงานภาพยนตร์ที่สนใจมาประยุกต์เพื่อพัฒนาทักษะด้าน Cinematography",
    process: "วางแนวทางภาพ ออกแบบองค์ประกอบ มุมกล้อง และแสงให้เหมาะกับบรรยากาศของฉาก ก่อนนำฟุตเทจมาปรับแต่งสีเพื่อทดลองสร้าง Mood & Tone ในรูปแบบที่ต้องกา",
    contribution: "รับผิดชอบตำแหน่ง Director of Photography (DOP) ดูแลการออกแบบภาพ การจัดแสง การเลือกมุมกล้อง และควบคุมทิศทางด้าน Visual เพื่อให้ภาพสอดคล้องกับแนวคิดของงาน",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-13-gallery-1.jpg", "assets/project-13-gallery-2.jpg", "assets/project-13-gallery-3.jpg"]
  },
   {
    id: "project-18",
    number: "18",
    title: "ความฮักคือการให้",
    category: "MV",
    year: "2025",
    cover: "assets/project-18-cover.jpg",
    previewVideo: "assets/18.mp4",
    fullVideoUrl: "https://youtu.be/5Z9aM2woFdI?si=Nasoh-rSZd3l311j",
    role: "DOP / Editor",
    intro: "ผลงานในรายวิชาที่อยากท้าทายตัวเองโดยการ Shot on Iphone",
    overview: "Music Video ที่จัดทำขึ้นในรายวิชา โดยทดลองถ่ายทำด้วย iPhone เพื่อศึกษาการเล่าเรื่องผ่านภาพ การใช้แสงธรรมชาติ และการถ่ายทอดอารมณ์ของเพลงด้วยอุปกรณ์ที่มีอยู่",
    process: "วางแนวคิดและออกแบบรูปแบบภาพให้เข้ากับเนื้อหาเพลง วางแผนการถ่ายทำ เลือกมุมกล้องและช่วงเวลาแสง ก่อนนำฟุตเทจมาตัดต่อเพื่อเรียบเรียงจังหวะและอารมณ์ของ MV",
    contribution: "รับผิดชอบตำแหน่ง DOP / Editor ดูแลการออกแบบภาพ การถ่ายทำด้วย iPhone การเลือกมุมกล้อง รวมถึงการตัดต่อเพื่อสร้างลำดับภาพและบรรยากาศให้สอดคล้องกับเรื่องราวของเพลง",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-18-gallery-1.jpg", "assets/project-18-gallery-2.jpg", "assets/project-18-gallery-3.jpg"]
  },
     {
    id: "project-19",
    number: "19",
    title: "[ชื่อผลงานเกรดสี]",
    category: "SHORT FILM",
    year: "2026",
    cover: "assets/project-19-cover.jpg",
    previewVideo: "assets/19.mp4",
    fullVideoUrl: "https://youtu.be/5Z9aM2woFdI?si=Nasoh-rSZd3l311j",
    role: "Colorist",
    intro: "ใส่แนวคิดด้านสี เช่น การสร้างอารมณ์ การแยกช่วงเวลา หรือการทำให้ภาพจากหลายกล้องสอดคล้องกัน",
    overview: "อธิบาย source footage, reference, color space และเป้าหมายของการเกรดสี",
    process: "อธิบาย workflow ตั้งแต่ balancing, skin tone, look development, shot matching และ final output",
    contribution: "ระบุความท้าทายของฟุตเทจและวิธีแก้ เช่น mixed lighting, exposure mismatch หรือ noise",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-19-gallery-1.jpg", "assets/project-19-gallery-2.jpg", "assets/project-19-gallery-3.jpg"]
  },
     {
    id: "project-20",
    number: "20",
    title: "[ชื่อผลงานเกรดสี]",
    category: "SHORT FILM",
    year: "2026",
    cover: "assets/project-20-cover.jpg",
    previewVideo: "assets/20.mp4",
    fullVideoUrl: "https://youtu.be/5Z9aM2woFdI?si=Nasoh-rSZd3l311j",
    role: "Colorist",
    intro: "ใส่แนวคิดด้านสี เช่น การสร้างอารมณ์ การแยกช่วงเวลา หรือการทำให้ภาพจากหลายกล้องสอดคล้องกัน",
    overview: "อธิบาย source footage, reference, color space และเป้าหมายของการเกรดสี",
    process: "อธิบาย workflow ตั้งแต่ balancing, skin tone, look development, shot matching และ final output",
    contribution: "ระบุความท้าทายของฟุตเทจและวิธีแก้ เช่น mixed lighting, exposure mismatch หรือ noise",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-20-gallery-1.jpg", "assets/project-20-gallery-2.jpg", "assets/project-20-gallery-3.jpg"]
  },
     {
    id: "project-21",
    number: "21",
    title: "[ชื่อผลงานเกรดสี]",
    category: "โฆษณา",
    year: "2024",
    cover: "assets/project-21-cover.jpg",
    previewVideo: "assets/21.mp4",
    fullVideoUrl: "https://youtu.be/5Z9aM2woFdI?si=Nasoh-rSZd3l311j",
    role: "Colorist",
    intro: "ใส่แนวคิดด้านสี เช่น การสร้างอารมณ์ การแยกช่วงเวลา หรือการทำให้ภาพจากหลายกล้องสอดคล้องกัน",
    overview: "อธิบาย source footage, reference, color space และเป้าหมายของการเกรดสี",
    process: "อธิบาย workflow ตั้งแต่ balancing, skin tone, look development, shot matching และ final output",
    contribution: "ระบุความท้าทายของฟุตเทจและวิธีแก้ เช่น mixed lighting, exposure mismatch หรือ noise",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-21-gallery-1.jpg", "assets/project-21-gallery-2.jpg", "assets/project-21-gallery-3.jpg"]
  },
     {
    id: "project-22",
    number: "22",
    title: "[ชื่อผลงานเกรดสี]",
    category: "คลิปสั้น",
    year: "2026",
    cover: "assets/project-22-cover.jpg",
    previewVideo: "assets/22.mp4",
    fullVideoUrl: "https://youtu.be/5Z9aM2woFdI?si=Nasoh-rSZd3l311j",
    role: "Colorist",
    intro: "ใส่แนวคิดด้านสี เช่น การสร้างอารมณ์ การแยกช่วงเวลา หรือการทำให้ภาพจากหลายกล้องสอดคล้องกัน",
    overview: "อธิบาย source footage, reference, color space และเป้าหมายของการเกรดสี",
    process: "อธิบาย workflow ตั้งแต่ balancing, skin tone, look development, shot matching และ final output",
    contribution: "ระบุความท้าทายของฟุตเทจและวิธีแก้ เช่น mixed lighting, exposure mismatch หรือ noise",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-22-gallery-1.jpg", "assets/project-22-gallery-2.jpg", "assets/project-22-gallery-3.jpg"]
  },
     {
    id: "project-23",
    number: "23",
    title: "[ชื่อผลงานเกรดสี]",
    category: "MV",
    year: "2025",
    cover: "assets/project-23-cover.jpg",
    previewVideo: "assets/23.mp4",
    fullVideoUrl: "https://youtu.be/5Z9aM2woFdI?si=Nasoh-rSZd3l311j",
    role: "Colorist",
    intro: "ใส่แนวคิดด้านสี เช่น การสร้างอารมณ์ การแยกช่วงเวลา หรือการทำให้ภาพจากหลายกล้องสอดคล้องกัน",
    overview: "อธิบาย source footage, reference, color space และเป้าหมายของการเกรดสี",
    process: "อธิบาย workflow ตั้งแต่ balancing, skin tone, look development, shot matching และ final output",
    contribution: "ระบุความท้าทายของฟุตเทจและวิธีแก้ เช่น mixed lighting, exposure mismatch หรือ noise",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-23-gallery-1.jpg", "assets/project-23-gallery-2.jpg", "assets/project-23-gallery-3.jpg"]
  },
     {
    id: "project-24",
    number: "24",
    title: "[ชื่อผลงานเกรดสี]",
    category: "คลิปสั้น",
    year: "2025",
    cover: "assets/project-24-cover.jpg",
    previewVideo: "assets/24.mp4",
    fullVideoUrl: "https://youtu.be/5Z9aM2woFdI?si=Nasoh-rSZd3l311j",
    role: "Colorist",
    intro: "ใส่แนวคิดด้านสี เช่น การสร้างอารมณ์ การแยกช่วงเวลา หรือการทำให้ภาพจากหลายกล้องสอดคล้องกัน",
    overview: "อธิบาย source footage, reference, color space และเป้าหมายของการเกรดสี",
    process: "อธิบาย workflow ตั้งแต่ balancing, skin tone, look development, shot matching และ final output",
    contribution: "ระบุความท้าทายของฟุตเทจและวิธีแก้ เช่น mixed lighting, exposure mismatch หรือ noise",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-24-gallery-1.jpg", "assets/project-24-gallery-2.jpg", "assets/project-24-gallery-3.jpg"]
  },
       {
    id: "project-25",
    number: "25",
    title: "[ชื่อผลงานเกรดสี]",
    category: "SHORT FILM",
    year: "2026",
    cover: "assets/project-25-cover.jpg",
    previewVideo: "assets/25.mp4",
    fullVideoUrl: "https://drive.google.com/file/d/1TlduCXmXn8z1s5AsbeolzoohIks_q2eU/view",
    role: "Colorist",
    intro: "ใส่แนวคิดด้านสี เช่น การสร้างอารมณ์ การแยกช่วงเวลา หรือการทำให้ภาพจากหลายกล้องสอดคล้องกัน",
    overview: "อธิบาย source footage, reference, color space และเป้าหมายของการเกรดสี",
    process: "อธิบาย workflow ตั้งแต่ balancing, skin tone, look development, shot matching และ final output",
    contribution: "ระบุความท้าทายของฟุตเทจและวิธีแก้ เช่น mixed lighting, exposure mismatch หรือ noise",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-25-gallery-1.jpg", "assets/project-25-gallery-2.jpg", "assets/project-25-gallery-3.jpg"]
  },
       {
    id: "project-26",
    number: "26",
    title: "[ชื่อผลงานเกรดสี]",
    category: "MV",
    year: "2026",
    cover: "assets/project-26-cover.jpg",
    previewVideo: "assets/26.mp4",
    fullVideoUrl: "https://youtu.be/ofd73CEAUzQ?si=ESBqiTYkEuGhYOsv",
    role: "Colorist",
    intro: "ใส่แนวคิดด้านสี เช่น การสร้างอารมณ์ การแยกช่วงเวลา หรือการทำให้ภาพจากหลายกล้องสอดคล้องกัน",
    overview: "อธิบาย source footage, reference, color space และเป้าหมายของการเกรดสี",
    process: "อธิบาย workflow ตั้งแต่ balancing, skin tone, look development, shot matching และ final output",
    contribution: "ระบุความท้าทายของฟุตเทจและวิธีแก้ เช่น mixed lighting, exposure mismatch หรือ noise",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-26-gallery-1.jpg", "assets/project-26-gallery-2.jpg", "assets/project-26-gallery-3.jpg"]
  },
       {
    id: "project-27",
    number: "27",
    title: "[ชื่อผลงานเกรดสี]",
    category: "คลิปสั้น",
    year: "2025",
    cover: "assets/project-27-cover.jpg",
    previewVideo: "assets/27.mp4",
    fullVideoUrl: "https://web.facebook.com/share/p/1Bu1UukLvP/",
    role: "Colorist",
    intro: "ใส่แนวคิดด้านสี เช่น การสร้างอารมณ์ การแยกช่วงเวลา หรือการทำให้ภาพจากหลายกล้องสอดคล้องกัน",
    overview: "อธิบาย source footage, reference, color space และเป้าหมายของการเกรดสี",
    process: "อธิบาย workflow ตั้งแต่ balancing, skin tone, look development, shot matching และ final output",
    contribution: "ระบุความท้าทายของฟุตเทจและวิธีแก้ เช่น mixed lighting, exposure mismatch หรือ noise",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-27-gallery-1.jpg", "assets/project-27-gallery-2.jpg", "assets/project-27-gallery-3.jpg"]
  },

       {
    id: "project-28",
    number: "28",
    title: "[ชื่อผลงานเกรดสี]",
    category: "คลิปสั้น",
    year: "2025",
    cover: "assets/project-28-cover.jpg",
    previewVideo: "assets/28.mp4",
    fullVideoUrl: "https://youtu.be/5Z9aM2woFdI?si=Nasoh-rSZd3l311j",
    role: "Colorist",
    intro: "ใส่แนวคิดด้านสี เช่น การสร้างอารมณ์ การแยกช่วงเวลา หรือการทำให้ภาพจากหลายกล้องสอดคล้องกัน",
    overview: "อธิบาย source footage, reference, color space และเป้าหมายของการเกรดสี",
    process: "อธิบาย workflow ตั้งแต่ balancing, skin tone, look development, shot matching และ final output",
    contribution: "ระบุความท้าทายของฟุตเทจและวิธีแก้ เช่น mixed lighting, exposure mismatch หรือ noise",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-28-gallery-1.jpg", "assets/project-28-gallery-2.jpg", "assets/project-28-gallery-3.jpg"]
  },
       {
    id: "project-29",
    number: "29",
    title: "[ชื่อผลงานเกรดสี]",
    category: "คลิปสั้น",
    year: "2025",
    cover: "assets/project-29-cover.jpg",
    previewVideo: "assets/29.mp4",
    fullVideoUrl: "https://youtu.be/5Z9aM2woFdI?si=Nasoh-rSZd3l311j",
    role: "Colorist",
    intro: "ใส่แนวคิดด้านสี เช่น การสร้างอารมณ์ การแยกช่วงเวลา หรือการทำให้ภาพจากหลายกล้องสอดคล้องกัน",
    overview: "อธิบาย source footage, reference, color space และเป้าหมายของการเกรดสี",
    process: "อธิบาย workflow ตั้งแต่ balancing, skin tone, look development, shot matching และ final output",
    contribution: "ระบุความท้าทายของฟุตเทจและวิธีแก้ เช่น mixed lighting, exposure mismatch หรือ noise",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-29-gallery-1.jpg", "assets/project-29-gallery-2.jpg", "assets/project-29-gallery-3.jpg"]
  },
      {
    id: "project-30",
    number: "30",
    title: "[ชื่อผลงานเกรดสี]",
    category: "SHORT FILM",
    year: "2026",
    cover: "assets/project-30-cover.jpg",
    previewVideo: "assets/30.mp4",
    fullVideoUrl: "https://youtu.be/5Z9aM2woFdI?si=Nasoh-rSZd3l311j",
    role: "Colorist",
    intro: "ใส่แนวคิดด้านสี เช่น การสร้างอารมณ์ การแยกช่วงเวลา หรือการทำให้ภาพจากหลายกล้องสอดคล้องกัน",
    overview: "อธิบาย source footage, reference, color space และเป้าหมายของการเกรดสี",
    process: "อธิบาย workflow ตั้งแต่ balancing, skin tone, look development, shot matching และ final output",
    contribution: "ระบุความท้าทายของฟุตเทจและวิธีแก้ เช่น mixed lighting, exposure mismatch หรือ noise",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-30-gallery-1.jpg", "assets/project-30-gallery-2.jpg", "assets/project-30-gallery-3.jpg"]
  },
];


// ผลงานเพิ่มเติมที่ร่วมฝึกงานกับโปรดักชั่นพี่
// เปลี่ยน poster, video และ url ให้เป็นภาพปก/คลิปตัวอย่าง/ลิงก์จริงของคุณได้ที่นี่
const ADDITIONAL_WORKS = [
  {
    title: "ผลงานร่วมกับพี่ 01",
    poster: "assets/project-01-stardust.jpg",
    video: "assets/internship-01-preview.mp4",
    url: "https://youtu.be/43QGSf0rCQg?si=ou1D2UeIZacvHWUN"
  },
  {
    title: "ผลงานร่วมกับพี่ 02",
    poster: "assets/project-02-stardust.jpg",
    video: "assets/internship-02-preview.mp4",
    url: "https://www.facebook.com/share/v/1957dVxpcM/"
  },
  {
    title: "ผลงานร่วมกับพี่ 03",
    poster: "assets/project-03-stardust.jpg",
    video: "assets/internship-03-preview.mp4",
    url: "https://youtu.be/hkIeYM1tuPs?si=Q4S2bWATozGQp6jx"
  },
  {
    title: "ผลงานร่วมกับพี่ 04",
    poster: "assets/project-04-stardust.jpg",
    video: "assets/internship-04-preview.mp4",
    url: "https://www.facebook.com/share/v/1D7bnr96A5/"
  },
  {
    title: "ผลงานร่วมกับพี่ 05",
    poster: "assets/project-05-stardust.jpg",
    video: "assets/internship-05-preview.mp4",
    url: "https://youtu.be/S8qCuJsaHeQ?si=mywGp9SEpXJKjPyd"
  },
    {
    title: "ผลงานร่วมกับพี่ 06",
    poster: "assets/project-06-stardust.jpg",
    video: "assets/internship-06-preview.mp4",
    url: "https://youtu.be/J-8jSFiP9BM?si=uycrtTWmswLxfdFH"
  }
];
