// แก้ข้อมูลผลงานได้ที่ไฟล์นี้ไฟล์เดียว
const PROJECTS = [
  {
    id: "short-film",
    number: "01",
    title: "[ชื่อผลงานหนังสั้น]",
    category: "SHORT FILM",
    year: "2025",
    cover: "assets/project-01-cover.jpg",
    previewVideo: "assets/1.mp4",
    fullVideoUrl: "https://youtu.be/zCyQyW--qZs?si=7qJ0BBYGQvak4lca",
    role: "Director / DOP / Lighting / Colorist",
    intro: "ใส่คำโปรยสั้น ๆ ของผลงาน เช่น แนวคิดหลัก เรื่องย่อ หรือโจทย์ที่ทีมได้รับ ไม่ควรเกิน 2–3 บรรทัด",
    overview: "ใส่รายละเอียดภาพรวมของโปรเจกต์นี้ เช่น วัตถุประสงค์ กลุ่มเป้าหมาย ระยะเวลาการผลิต และสิ่งที่ต้องการสื่อสารผ่านงานภาพ",
    process: "อธิบายกระบวนการทำงานของคุณตั้งแต่ Pre-production, Production และ Post-production รวมถึงการวางภาพ แสง การเคลื่อนกล้อง และการเกรดสี",
    contribution: "ระบุหน้าที่ที่คุณรับผิดชอบจริง พร้อมปัญหาที่พบและวิธีแก้ไข เพื่อให้ผู้คัดเลือกเห็นวิธีคิดและการทำงานของคุณ",
    credits: ["Production: [ชื่อทีม]", "Camera: [รุ่นกล้อง / เลนส์]", "Duration: [ระยะเวลา]"],
    gallery: ["assets/project-01-gallery-1.jpg", "assets/project-01-gallery-2.jpg", "assets/project-01-gallery-3.jpg"]
  },
  {
    id: "commercial",
    number: "02",
    title: "[ชื่อผลงานโฆษณา]",
    category: "SHORT FILM",
    year: "2025",
    cover: "assets/project-02-cover.jpg",
    previewVideo: "assets/2.mp4",
    fullVideoUrl: "https://www.youtube.com/watch?v=RZPY1lr7Bas&t=1s",
    role: "DOP / Camera Operator",
    intro: "ใส่คำโปรยของผลงานโฆษณา บอกโจทย์แบรนด์และภาพลักษณ์ที่ต้องการสื่อสาร",
    overview: "อธิบายโจทย์ของแบรนด์ กลุ่มเป้าหมาย รูปแบบสื่อ และแนวคิดภาพรวมของการถ่ายทำ",
    process: "อธิบายการเลือกมุมกล้อง เลนส์ การจัดแสง และการควบคุม mood & tone ให้สอดคล้องกับแบรนด์",
    contribution: "ระบุสิ่งที่คุณทำจริงในกอง เช่น shot list, camera setup, lighting setup หรือการประสานงานกับทีม",
    credits: ["Client: [ชื่อแบรนด์]", "Agency: [ถ้ามี]", "Deliverables: [เช่น 16:9 / 9:16]"],
    gallery: ["assets/project-02-gallery-1.jpg", "assets/project-02-gallery-2.jpg", "assets/project-02-gallery-3.jpg"]
  },
  {
    id: "music-video",
    number: "03",
    title: "[ชื่อผลงานมิวสิกวิดีโอ]",
    category: "SHORT FILM",
    year: "2025",
    cover: "assets/project-03-cover.jpg",
    previewVideo: "assets/3.mp4",
    fullVideoUrl: "https://www.youtube.com/watch?v=-A8LKJcPT2E&t=1s",
    role: "Director / DOP",
    intro: "ใส่แนวคิดของมิวสิกวิดีโอและความสัมพันธ์ระหว่างภาพ ดนตรี และอารมณ์ของเพลง",
    overview: "อธิบาย narrative, visual reference, color palette และรูปแบบการเล่าเรื่องที่เลือกใช้",
    process: "อธิบายการวาง blocking, camera movement, lighting และจังหวะการตัดต่อให้สัมพันธ์กับเพลง",
    contribution: "ระบุความรับผิดชอบของคุณ และสิ่งที่ทำให้ผลงานนี้สะท้อนสไตล์การทำภาพของคุณ",
    credits: ["Artist: [ชื่อศิลปิน]", "Track: [ชื่อเพลง]", "Runtime: [ความยาว]"],
    gallery: ["assets/project-03-gallery-1.jpg", "assets/project-03-gallery-2.jpg", "assets/project-03-gallery-3.jpg"]
  },
  {
    id: "documentary",
    number: "04",
    title: "[ชื่อผลงานสารคดี]",
    category: "โฆษณา",
    year: "2026",
    cover: "assets/project-04-cover.jpg",
    previewVideo: "assets/4.mp4",
    fullVideoUrl: "https://youtu.be/_oOxiBekvUk?si=4jKAeD5lyr9jzrI-",
    role: "Camera Operator / Focus Puller",
    intro: "ใส่ประเด็นของสารคดี บุคคลหรือชุมชนที่ติดตาม และสิ่งที่ต้องการให้ผู้ชมได้รับ",
    overview: "อธิบายบริบทการถ่ายทำ ข้อจำกัดด้านสถานที่ เวลา หรือการเข้าถึงตัวละคร",
    process: "อธิบายวิธีการทำงานแบบ observational หรือ interview-based รวมถึงการเตรียมอุปกรณ์และการรับมือสถานการณ์จริง",
    contribution: "ระบุบทบาทในกองและตัวอย่างการตัดสินใจหน้างานที่ช่วยให้ได้ภาพสำคัญ",
    credits: ["Subject: [หัวข้อ]", "Location: [สถานที่]", "Format: [รูปแบบ]"],
    gallery: ["assets/project-04-gallery-1.jpg", "assets/project-04-gallery-2.jpg", "assets/project-04-gallery-3.jpg"]
  },
  {
    id: "social-content",
    number: "05",
    title: "[ชื่อแคมเปญหรือคอนเทนต์]",
    category: "SHORT FILM",
    year: "2025",
    cover: "assets/project-05-cover.jpg",
    previewVideo: "assets/5.mp4",
    fullVideoUrl: "https://youtu.be/Nfhscrl5iTo?si=_pZ5seU6wR4xhWQ_",
    role: "Camera / Video Editor",
    intro: "ใส่แนวคิดของคอนเทนต์ แพลตฟอร์มที่เผยแพร่ และพฤติกรรมผู้ชมที่ต้องการตอบโจทย์",
    overview: "อธิบายรูปแบบซีรีส์คอนเทนต์ จำนวนชิ้นงาน และข้อกำหนดของแต่ละแพลตฟอร์ม",
    process: "อธิบายการวาง hook, pacing, framing สำหรับแนวตั้ง และ workflow การตัดต่อ",
    contribution: "ระบุงานที่รับผิดชอบตั้งแต่ถ่ายทำจนถึงส่งออกไฟล์ รวมถึงการจัดการเวลาและเวอร์ชันงาน",
    credits: ["Platform: [TikTok / Reels / YouTube]", "Episodes: [จำนวน]", "Format: [9:16 / 1:1]"],
    gallery: ["assets/project-05-gallery-1.jpg", "assets/project-05-gallery-2.jpg", "assets/project-05-gallery-3.jpg"]
  },
  {
    id: "color-study",
    number: "06",
    title: "[ชื่อผลงานเกรดสี]",
    category: "SHORT FILM",
    year: "2025",
    cover: "assets/project-06-cover.jpg",
    previewVideo: "assets/6.mp4",
    fullVideoUrl: "https://youtu.be/A_Rq_f_PX7I?si=GZ94DBHca6oD1vve",
    role: "Colorist",
    intro: "ใส่แนวคิดด้านสี เช่น การสร้างอารมณ์ การแยกช่วงเวลา หรือการทำให้ภาพจากหลายกล้องสอดคล้องกัน",
    overview: "อธิบาย source footage, reference, color space และเป้าหมายของการเกรดสี",
    process: "อธิบาย workflow ตั้งแต่ balancing, skin tone, look development, shot matching และ final output",
    contribution: "ระบุความท้าทายของฟุตเทจและวิธีแก้ เช่น mixed lighting, exposure mismatch หรือ noise",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-06-gallery-1.jpg", "assets/project-06-gallery-2.jpg", "assets/project-06-gallery-3.jpg"]
  },
  {
    id: "project-07",
    number: "07",
    title: "[ชื่อผลงานเกรดสี]",
    category: "โฆษณา",
    year: "2026",
    cover: "assets/project-07-cover.jpg",
    previewVideo: "assets/7.mp4",
    fullVideoUrl: "",
    role: "Colorist",
    intro: "ใส่แนวคิดด้านสี เช่น การสร้างอารมณ์ การแยกช่วงเวลา หรือการทำให้ภาพจากหลายกล้องสอดคล้องกัน",
    overview: "อธิบาย source footage, reference, color space และเป้าหมายของการเกรดสี",
    process: "อธิบาย workflow ตั้งแต่ balancing, skin tone, look development, shot matching และ final output",
    contribution: "ระบุความท้าทายของฟุตเทจและวิธีแก้ เช่น mixed lighting, exposure mismatch หรือ noise",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-07-gallery-1.jpg", "assets/project-07-gallery-2.jpg", "assets/project-07-gallery-3.jpg"]
  },
  {
    id: "project-08",
    number: "08",
    title: "[ชื่อผลงานเกรดสี]",
    category: "โฆษณา",
    year: "2025",
    cover: "assets/project-08-cover.jpg",
    previewVideo: "assets/8.mp4",
    fullVideoUrl: "https://web.facebook.com/share/v/14qwpn1bgJc/",
    role: "Colorist",
    intro: "ใส่แนวคิดด้านสี เช่น การสร้างอารมณ์ การแยกช่วงเวลา หรือการทำให้ภาพจากหลายกล้องสอดคล้องกัน",
    overview: "อธิบาย source footage, reference, color space และเป้าหมายของการเกรดสี",
    process: "อธิบาย workflow ตั้งแต่ balancing, skin tone, look development, shot matching และ final output",
    contribution: "ระบุความท้าทายของฟุตเทจและวิธีแก้ เช่น mixed lighting, exposure mismatch หรือ noise",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-08-gallery-1.jpg", "assets/project-08-gallery-2.jpg", "assets/project-08-gallery-3.jpg"]
  },
  {
    id: "project-09",
    number: "09",
    title: "[ชื่อผลงานเกรดสี]",
    category: "SHORT FILM",
    year: "2025",
    cover: "assets/project-09-cover.jpg",
    previewVideo: "assets/9.mp4",
    fullVideoUrl: "https://youtu.be/GGHmVqOZv-8?si=RYXW694_RCgD004H",
    role: "Colorist",
    intro: "ใส่แนวคิดด้านสี เช่น การสร้างอารมณ์ การแยกช่วงเวลา หรือการทำให้ภาพจากหลายกล้องสอดคล้องกัน",
    overview: "อธิบาย source footage, reference, color space และเป้าหมายของการเกรดสี",
    process: "อธิบาย workflow ตั้งแต่ balancing, skin tone, look development, shot matching และ final output",
    contribution: "ระบุความท้าทายของฟุตเทจและวิธีแก้ เช่น mixed lighting, exposure mismatch หรือ noise",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-09-gallery-1.jpg", "assets/project-09-gallery-2.jpg", "assets/project-09-gallery-3.jpg"]
  },
  {
    id: "project-10",
    number: "10",
    title: "[ชื่อผลงานเกรดสี]",
    category: "คลิปสั้น",
    year: "2026",
    cover: "assets/project-10-cover.jpg",
    previewVideo: "assets/10.mp4",
    fullVideoUrl: "",
    role: "Colorist",
    intro: "ใส่แนวคิดด้านสี เช่น การสร้างอารมณ์ การแยกช่วงเวลา หรือการทำให้ภาพจากหลายกล้องสอดคล้องกัน",
    overview: "อธิบาย source footage, reference, color space และเป้าหมายของการเกรดสี",
    process: "อธิบาย workflow ตั้งแต่ balancing, skin tone, look development, shot matching และ final output",
    contribution: "ระบุความท้าทายของฟุตเทจและวิธีแก้ เช่น mixed lighting, exposure mismatch หรือ noise",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-10-gallery-1.jpg", "assets/project-10-gallery-2.jpg", "assets/project-10-gallery-3.jpg"]
  },
  {
    id: "project-11",
    number: "11",
    title: "[ชื่อผลงานเกรดสี]",
    category: "MV",
    year: "2026",
    cover: "assets/project-11-cover.jpg",
    previewVideo: "assets/11.mp4",
    fullVideoUrl: "",
    role: "Colorist",
    intro: "ใส่แนวคิดด้านสี เช่น การสร้างอารมณ์ การแยกช่วงเวลา หรือการทำให้ภาพจากหลายกล้องสอดคล้องกัน",
    overview: "อธิบาย source footage, reference, color space และเป้าหมายของการเกรดสี",
    process: "อธิบาย workflow ตั้งแต่ balancing, skin tone, look development, shot matching และ final output",
    contribution: "ระบุความท้าทายของฟุตเทจและวิธีแก้ เช่น mixed lighting, exposure mismatch หรือ noise",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-11-gallery-1.jpg", "assets/project-11-gallery-2.jpg", "assets/project-11-gallery-3.jpg"]
  },
  {
    id: "project-12",
    number: "12",
    title: "[ชื่อผลงานเกรดสี]",
    category: "คลิปสั้น",
    year: "2025",
    cover: "assets/project-12-cover.jpg",
    previewVideo: "assets/12.mp4",
    fullVideoUrl: "",
    role: "Colorist",
    intro: "ใส่แนวคิดด้านสี เช่น การสร้างอารมณ์ การแยกช่วงเวลา หรือการทำให้ภาพจากหลายกล้องสอดคล้องกัน",
    overview: "อธิบาย source footage, reference, color space และเป้าหมายของการเกรดสี",
    process: "อธิบาย workflow ตั้งแต่ balancing, skin tone, look development, shot matching และ final output",
    contribution: "ระบุความท้าทายของฟุตเทจและวิธีแก้ เช่น mixed lighting, exposure mismatch หรือ noise",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-12-gallery-1.jpg", "assets/project-12-gallery-2.jpg", "assets/project-12-gallery-3.jpg"]
  },
  {
    id: "project-13",
    number: "13",
    title: "[ชื่อผลงานเกรดสี]",
    category: "SHORT FILM",
    year: "2026",
    cover: "assets/project-13-cover.jpg",
    previewVideo: "assets/13.mp4",
    fullVideoUrl: "https://www.youtube.com/watch?v=-nVAvTxNz60&t=702s",
    role: "Colorist",
    intro: "ใส่แนวคิดด้านสี เช่น การสร้างอารมณ์ การแยกช่วงเวลา หรือการทำให้ภาพจากหลายกล้องสอดคล้องกัน",
    overview: "อธิบาย source footage, reference, color space และเป้าหมายของการเกรดสี",
    process: "อธิบาย workflow ตั้งแต่ balancing, skin tone, look development, shot matching และ final output",
    contribution: "ระบุความท้าทายของฟุตเทจและวิธีแก้ เช่น mixed lighting, exposure mismatch หรือ noise",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-13-gallery-1.jpg", "assets/project-13-gallery-2.jpg", "assets/project-13-gallery-3.jpg"]
  },
  {
    id: "project-14",
    number: "14",
    title: "[ชื่อผลงานเกรดสี]",
    category: "SHORT FILM",
    year: "2026",
    cover: "assets/project-14-cover.jpg",
    previewVideo: "assets/14.mp4",
    fullVideoUrl: "",
    role: "Colorist",
    intro: "ใส่แนวคิดด้านสี เช่น การสร้างอารมณ์ การแยกช่วงเวลา หรือการทำให้ภาพจากหลายกล้องสอดคล้องกัน",
    overview: "อธิบาย source footage, reference, color space และเป้าหมายของการเกรดสี",
    process: "อธิบาย workflow ตั้งแต่ balancing, skin tone, look development, shot matching และ final output",
    contribution: "ระบุความท้าทายของฟุตเทจและวิธีแก้ เช่น mixed lighting, exposure mismatch หรือ noise",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-13-gallery-1.jpg", "assets/project-13-gallery-2.jpg", "assets/project-13-gallery-3.jpg"]
  },
  {
    id: "project-15",
    number: "15",
    title: "[ชื่อผลงานเกรดสี]",
    category: "SHORT FILM",
    year: "2026",
    cover: "assets/project-15-cover.jpg",
    previewVideo: "assets/15.mp4",
    fullVideoUrl: "",
    role: "Colorist",
    intro: "ใส่แนวคิดด้านสี เช่น การสร้างอารมณ์ การแยกช่วงเวลา หรือการทำให้ภาพจากหลายกล้องสอดคล้องกัน",
    overview: "อธิบาย source footage, reference, color space และเป้าหมายของการเกรดสี",
    process: "อธิบาย workflow ตั้งแต่ balancing, skin tone, look development, shot matching และ final output",
    contribution: "ระบุความท้าทายของฟุตเทจและวิธีแก้ เช่น mixed lighting, exposure mismatch หรือ noise",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-13-gallery-1.jpg", "assets/project-13-gallery-2.jpg", "assets/project-13-gallery-3.jpg"]
  },
  {
    id: "project-16",
    number: "16",
    title: "[ชื่อผลงานเกรดสี]",
    category: "SHORT FILM",
    year: "2026",
    cover: "assets/project-16-cover.jpg",
    previewVideo: "assets/16.mp4",
    fullVideoUrl: "https://drive.google.com/file/d/1PZZBFQ1JkIoeIuwywbqhPd3ZeOvhmoE-/view?usp=sharing",
    role: "Colorist",
    intro: "ใส่แนวคิดด้านสี เช่น การสร้างอารมณ์ การแยกช่วงเวลา หรือการทำให้ภาพจากหลายกล้องสอดคล้องกัน",
    overview: "อธิบาย source footage, reference, color space และเป้าหมายของการเกรดสี",
    process: "อธิบาย workflow ตั้งแต่ balancing, skin tone, look development, shot matching และ final output",
    contribution: "ระบุความท้าทายของฟุตเทจและวิธีแก้ เช่น mixed lighting, exposure mismatch หรือ noise",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-13-gallery-1.jpg", "assets/project-13-gallery-2.jpg", "assets/project-13-gallery-3.jpg"]
  },
  {
    id: "project-17",
    number: "17",
    title: "[ชื่อผลงานเกรดสี]",
    category: "คลิปสั้น",
    year: "2026",
    cover: "assets/project-17-cover.jpg",
    previewVideo: "assets/17.mp4",
    fullVideoUrl: "https://youtu.be/NhWuvCCQI34?si=DGFolkYNNaAMf39f",
    role: "Colorist",
    intro: "ใส่แนวคิดด้านสี เช่น การสร้างอารมณ์ การแยกช่วงเวลา หรือการทำให้ภาพจากหลายกล้องสอดคล้องกัน",
    overview: "อธิบาย source footage, reference, color space และเป้าหมายของการเกรดสี",
    process: "อธิบาย workflow ตั้งแต่ balancing, skin tone, look development, shot matching และ final output",
    contribution: "ระบุความท้าทายของฟุตเทจและวิธีแก้ เช่น mixed lighting, exposure mismatch หรือ noise",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-13-gallery-1.jpg", "assets/project-13-gallery-2.jpg", "assets/project-13-gallery-3.jpg"]
  },
   {
    id: "project-18",
    number: "18",
    title: "[ชื่อผลงานเกรดสี]",
    category: "MV",
    year: "2025",
    cover: "assets/project-18-cover.jpg",
    previewVideo: "assets/18.mp4",
    fullVideoUrl: "https://youtu.be/5Z9aM2woFdI?si=Nasoh-rSZd3l311j",
    role: "Colorist",
    intro: "ใส่แนวคิดด้านสี เช่น การสร้างอารมณ์ การแยกช่วงเวลา หรือการทำให้ภาพจากหลายกล้องสอดคล้องกัน",
    overview: "อธิบาย source footage, reference, color space และเป้าหมายของการเกรดสี",
    process: "อธิบาย workflow ตั้งแต่ balancing, skin tone, look development, shot matching และ final output",
    contribution: "ระบุความท้าทายของฟุตเทจและวิธีแก้ เช่น mixed lighting, exposure mismatch หรือ noise",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-18-gallery-1.jpg", "assets/project-18-gallery-2.jpg", "assets/project-18-gallery-3.jpg"]
  },
     {
    id: "project-19",
    number: "19",
    title: "[ชื่อผลงานเกรดสี]",
    category: "SHORT FILM",
    year: "2026",
    cover: "assets/project-19-cover.jpg",
    previewVideo: "assets/19.mp4",
    fullVideoUrl: "https://youtu.be/5Z9aM2woFdI?si=Nasoh-rSZd3l311j",
    role: "Colorist",
    intro: "ใส่แนวคิดด้านสี เช่น การสร้างอารมณ์ การแยกช่วงเวลา หรือการทำให้ภาพจากหลายกล้องสอดคล้องกัน",
    overview: "อธิบาย source footage, reference, color space และเป้าหมายของการเกรดสี",
    process: "อธิบาย workflow ตั้งแต่ balancing, skin tone, look development, shot matching และ final output",
    contribution: "ระบุความท้าทายของฟุตเทจและวิธีแก้ เช่น mixed lighting, exposure mismatch หรือ noise",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-19-gallery-1.jpg", "assets/project-19-gallery-2.jpg", "assets/project-19-gallery-3.jpg"]
  },
     {
    id: "project-20",
    number: "20",
    title: "[ชื่อผลงานเกรดสี]",
    category: "SHORT FILM",
    year: "2026",
    cover: "assets/project-20-cover.jpg",
    previewVideo: "assets/20.mp4",
    fullVideoUrl: "https://youtu.be/5Z9aM2woFdI?si=Nasoh-rSZd3l311j",
    role: "Colorist",
    intro: "ใส่แนวคิดด้านสี เช่น การสร้างอารมณ์ การแยกช่วงเวลา หรือการทำให้ภาพจากหลายกล้องสอดคล้องกัน",
    overview: "อธิบาย source footage, reference, color space และเป้าหมายของการเกรดสี",
    process: "อธิบาย workflow ตั้งแต่ balancing, skin tone, look development, shot matching และ final output",
    contribution: "ระบุความท้าทายของฟุตเทจและวิธีแก้ เช่น mixed lighting, exposure mismatch หรือ noise",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-20-gallery-1.jpg", "assets/project-20-gallery-2.jpg", "assets/project-20-gallery-3.jpg"]
  },
     {
    id: "project-21",
    number: "21",
    title: "[ชื่อผลงานเกรดสี]",
    category: "โฆษณา",
    year: "2024",
    cover: "assets/project-21-cover.jpg",
    previewVideo: "assets/21.mp4",
    fullVideoUrl: "https://youtu.be/5Z9aM2woFdI?si=Nasoh-rSZd3l311j",
    role: "Colorist",
    intro: "ใส่แนวคิดด้านสี เช่น การสร้างอารมณ์ การแยกช่วงเวลา หรือการทำให้ภาพจากหลายกล้องสอดคล้องกัน",
    overview: "อธิบาย source footage, reference, color space และเป้าหมายของการเกรดสี",
    process: "อธิบาย workflow ตั้งแต่ balancing, skin tone, look development, shot matching และ final output",
    contribution: "ระบุความท้าทายของฟุตเทจและวิธีแก้ เช่น mixed lighting, exposure mismatch หรือ noise",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-21-gallery-1.jpg", "assets/project-21-gallery-2.jpg", "assets/project-21-gallery-3.jpg"]
  },
     {
    id: "project-22",
    number: "22",
    title: "[ชื่อผลงานเกรดสี]",
    category: "คลิปสั้น",
    year: "2026",
    cover: "assets/project-22-cover.jpg",
    previewVideo: "assets/22.mp4",
    fullVideoUrl: "https://youtu.be/5Z9aM2woFdI?si=Nasoh-rSZd3l311j",
    role: "Colorist",
    intro: "ใส่แนวคิดด้านสี เช่น การสร้างอารมณ์ การแยกช่วงเวลา หรือการทำให้ภาพจากหลายกล้องสอดคล้องกัน",
    overview: "อธิบาย source footage, reference, color space และเป้าหมายของการเกรดสี",
    process: "อธิบาย workflow ตั้งแต่ balancing, skin tone, look development, shot matching และ final output",
    contribution: "ระบุความท้าทายของฟุตเทจและวิธีแก้ เช่น mixed lighting, exposure mismatch หรือ noise",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-22-gallery-1.jpg", "assets/project-22-gallery-2.jpg", "assets/project-22-gallery-3.jpg"]
  },
     {
    id: "project-23",
    number: "23",
    title: "[ชื่อผลงานเกรดสี]",
    category: "MV",
    year: "2025",
    cover: "assets/project-23-cover.jpg",
    previewVideo: "assets/23.mp4",
    fullVideoUrl: "https://youtu.be/5Z9aM2woFdI?si=Nasoh-rSZd3l311j",
    role: "Colorist",
    intro: "ใส่แนวคิดด้านสี เช่น การสร้างอารมณ์ การแยกช่วงเวลา หรือการทำให้ภาพจากหลายกล้องสอดคล้องกัน",
    overview: "อธิบาย source footage, reference, color space และเป้าหมายของการเกรดสี",
    process: "อธิบาย workflow ตั้งแต่ balancing, skin tone, look development, shot matching และ final output",
    contribution: "ระบุความท้าทายของฟุตเทจและวิธีแก้ เช่น mixed lighting, exposure mismatch หรือ noise",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-23-gallery-1.jpg", "assets/project-23-gallery-2.jpg", "assets/project-23-gallery-3.jpg"]
  },
     {
    id: "project-24",
    number: "24",
    title: "[ชื่อผลงานเกรดสี]",
    category: "คลิปสั้น",
    year: "2025",
    cover: "assets/project-24-cover.jpg",
    previewVideo: "assets/24.mp4",
    fullVideoUrl: "https://youtu.be/5Z9aM2woFdI?si=Nasoh-rSZd3l311j",
    role: "Colorist",
    intro: "ใส่แนวคิดด้านสี เช่น การสร้างอารมณ์ การแยกช่วงเวลา หรือการทำให้ภาพจากหลายกล้องสอดคล้องกัน",
    overview: "อธิบาย source footage, reference, color space และเป้าหมายของการเกรดสี",
    process: "อธิบาย workflow ตั้งแต่ balancing, skin tone, look development, shot matching และ final output",
    contribution: "ระบุความท้าทายของฟุตเทจและวิธีแก้ เช่น mixed lighting, exposure mismatch หรือ noise",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-24-gallery-1.jpg", "assets/project-24-gallery-2.jpg", "assets/project-24-gallery-3.jpg"]
  },
       {
    id: "project-25",
    number: "25",
    title: "[ชื่อผลงานเกรดสี]",
    category: "SHORT FILM",
    year: "2026",
    cover: "assets/project-25-cover.jpg",
    previewVideo: "assets/25.mp4",
    fullVideoUrl: "https://drive.google.com/file/d/1TlduCXmXn8z1s5AsbeolzoohIks_q2eU/view",
    role: "Colorist",
    intro: "ใส่แนวคิดด้านสี เช่น การสร้างอารมณ์ การแยกช่วงเวลา หรือการทำให้ภาพจากหลายกล้องสอดคล้องกัน",
    overview: "อธิบาย source footage, reference, color space และเป้าหมายของการเกรดสี",
    process: "อธิบาย workflow ตั้งแต่ balancing, skin tone, look development, shot matching และ final output",
    contribution: "ระบุความท้าทายของฟุตเทจและวิธีแก้ เช่น mixed lighting, exposure mismatch หรือ noise",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-25-gallery-1.jpg", "assets/project-25-gallery-2.jpg", "assets/project-25-gallery-3.jpg"]
  },
       {
    id: "project-26",
    number: "26",
    title: "[ชื่อผลงานเกรดสี]",
    category: "MV",
    year: "2026",
    cover: "assets/project-26-cover.jpg",
    previewVideo: "assets/26.mp4",
    fullVideoUrl: "https://youtu.be/ofd73CEAUzQ?si=ESBqiTYkEuGhYOsv",
    role: "Colorist",
    intro: "ใส่แนวคิดด้านสี เช่น การสร้างอารมณ์ การแยกช่วงเวลา หรือการทำให้ภาพจากหลายกล้องสอดคล้องกัน",
    overview: "อธิบาย source footage, reference, color space และเป้าหมายของการเกรดสี",
    process: "อธิบาย workflow ตั้งแต่ balancing, skin tone, look development, shot matching และ final output",
    contribution: "ระบุความท้าทายของฟุตเทจและวิธีแก้ เช่น mixed lighting, exposure mismatch หรือ noise",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-26-gallery-1.jpg", "assets/project-26-gallery-2.jpg", "assets/project-26-gallery-3.jpg"]
  },
       {
    id: "project-27",
    number: "27",
    title: "[ชื่อผลงานเกรดสี]",
    category: "คลิปสั้น",
    year: "2025",
    cover: "assets/project-27-cover.jpg",
    previewVideo: "assets/27.mp4",
    fullVideoUrl: "https://web.facebook.com/share/p/1Bu1UukLvP/",
    role: "Colorist",
    intro: "ใส่แนวคิดด้านสี เช่น การสร้างอารมณ์ การแยกช่วงเวลา หรือการทำให้ภาพจากหลายกล้องสอดคล้องกัน",
    overview: "อธิบาย source footage, reference, color space และเป้าหมายของการเกรดสี",
    process: "อธิบาย workflow ตั้งแต่ balancing, skin tone, look development, shot matching และ final output",
    contribution: "ระบุความท้าทายของฟุตเทจและวิธีแก้ เช่น mixed lighting, exposure mismatch หรือ noise",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-27-gallery-1.jpg", "assets/project-27-gallery-2.jpg", "assets/project-27-gallery-3.jpg"]
  },

       {
    id: "project-28",
    number: "28",
    title: "[ชื่อผลงานเกรดสี]",
    category: "คลิปสั้น",
    year: "2025",
    cover: "assets/project-28-cover.jpg",
    previewVideo: "assets/28.mp4",
    fullVideoUrl: "https://youtu.be/5Z9aM2woFdI?si=Nasoh-rSZd3l311j",
    role: "Colorist",
    intro: "ใส่แนวคิดด้านสี เช่น การสร้างอารมณ์ การแยกช่วงเวลา หรือการทำให้ภาพจากหลายกล้องสอดคล้องกัน",
    overview: "อธิบาย source footage, reference, color space และเป้าหมายของการเกรดสี",
    process: "อธิบาย workflow ตั้งแต่ balancing, skin tone, look development, shot matching และ final output",
    contribution: "ระบุความท้าทายของฟุตเทจและวิธีแก้ เช่น mixed lighting, exposure mismatch หรือ noise",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-28-gallery-1.jpg", "assets/project-28-gallery-2.jpg", "assets/project-28-gallery-3.jpg"]
  },
       {
    id: "project-29",
    number: "29",
    title: "[ชื่อผลงานเกรดสี]",
    category: "คลิปสั้น",
    year: "2025",
    cover: "assets/project-29-cover.jpg",
    previewVideo: "assets/29.mp4",
    fullVideoUrl: "https://youtu.be/5Z9aM2woFdI?si=Nasoh-rSZd3l311j",
    role: "Colorist",
    intro: "ใส่แนวคิดด้านสี เช่น การสร้างอารมณ์ การแยกช่วงเวลา หรือการทำให้ภาพจากหลายกล้องสอดคล้องกัน",
    overview: "อธิบาย source footage, reference, color space และเป้าหมายของการเกรดสี",
    process: "อธิบาย workflow ตั้งแต่ balancing, skin tone, look development, shot matching และ final output",
    contribution: "ระบุความท้าทายของฟุตเทจและวิธีแก้ เช่น mixed lighting, exposure mismatch หรือ noise",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-29-gallery-1.jpg", "assets/project-29-gallery-2.jpg", "assets/project-29-gallery-3.jpg"]
  },
      {
    id: "project-30",
    number: "30",
    title: "[ชื่อผลงานเกรดสี]",
    category: "SHORT FILM",
    year: "2026",
    cover: "assets/project-30-cover.jpg",
    previewVideo: "assets/30.mp4",
    fullVideoUrl: "https://youtu.be/5Z9aM2woFdI?si=Nasoh-rSZd3l311j",
    role: "Colorist",
    intro: "ใส่แนวคิดด้านสี เช่น การสร้างอารมณ์ การแยกช่วงเวลา หรือการทำให้ภาพจากหลายกล้องสอดคล้องกัน",
    overview: "อธิบาย source footage, reference, color space และเป้าหมายของการเกรดสี",
    process: "อธิบาย workflow ตั้งแต่ balancing, skin tone, look development, shot matching และ final output",
    contribution: "ระบุความท้าทายของฟุตเทจและวิธีแก้ เช่น mixed lighting, exposure mismatch หรือ noise",
    credits: ["Software: DaVinci Resolve", "Source: [กล้อง / Log profile]", "Delivery: [Rec.709 / อื่น ๆ]"],
    gallery: ["assets/project-30-gallery-1.jpg", "assets/project-30-gallery-2.jpg", "assets/project-30-gallery-3.jpg"]
  },
];


// ผลงานเพิ่มเติมที่ร่วมฝึกงานกับโปรดักชั่นพี่
// เปลี่ยน poster, video และ url ให้เป็นภาพปก/คลิปตัวอย่าง/ลิงก์จริงของคุณได้ที่นี่
const ADDITIONAL_WORKS = [
  {
    title: "ผลงานร่วมกับพี่ 01",
    poster: "assets/project-01-stardust.jpg",
    video: "assets/internship-01-preview.mp4",
    url: "https://youtu.be/43QGSf0rCQg?si=ou1D2UeIZacvHWUN"
  },
  {
    title: "ผลงานร่วมกับพี่ 02",
    poster: "assets/project-02-stardust.jpg",
    video: "assets/internship-02-preview.mp4",
    url: "https://www.facebook.com/share/v/1957dVxpcM/"
  },
  {
    title: "ผลงานร่วมกับพี่ 03",
    poster: "assets/project-03-stardust.jpg",
    video: "assets/internship-03-preview.mp4",
    url: "https://youtu.be/hkIeYM1tuPs?si=Q4S2bWATozGQp6jx"
  },
  {
    title: "ผลงานร่วมกับพี่ 04",
    poster: "assets/project-04-stardust.jpg",
    video: "assets/internship-04-preview.mp4",
    url: "https://www.facebook.com/share/v/1D7bnr96A5/"
  },
  {
    title: "ผลงานร่วมกับพี่ 05",
    poster: "assets/project-05-stardust.jpg",
    video: "assets/internship-05-preview.mp4",
    url: "https://youtu.be/S8qCuJsaHeQ?si=mywGp9SEpXJKjPyd"
  },
    {
    title: "ผลงานร่วมกับพี่ 06",
    poster: "assets/project-06-stardust.jpg",
    video: "assets/internship-06-preview.mp4",
    url: "https://youtu.be/J-8jSFiP9BM?si=uycrtTWmswLxfdFH"
  }
];
